#  menu items
[[main]]
   name = "ğŸ“°è‡ªç„¶è¯­è¨€å¤„ç†"
   weight = 1
   url = "nlp/"
   
 [[main]]
   name = "ğŸ—ï¸å¤§æ¨¡å‹åº”ç”¨"
   weight = 2
   url = "llm/"

 [[main]]
   name = "ğŸ’¸AIæ™ºèƒ½ä½“"
   weight = 3
   url = "agent/"

 [[main]]
   name = "ğŸ›¸SWUFEæ™ºèƒ½ä½“å¹³å°"
   weight = 4
   url = "http://agent.swufe.edu.cn/"

 [[main]]
   name = "ğŸ“AGIå›¢é˜Ÿ"
   weight = 5
   url = "https://www.swufenlp.group"   