#  menu items
[[main]]
   name = "ğŸ“°è‡ªç„¶è¯­è¨€å¤„ç†"
   weight = 1
   url = "nlp/"
   
 [[main]]
   name = "ğŸ—ï¸å¤§æ¨¡å‹åº”ç”¨"
   weight = 2
   url = "llm/"

 [[main]]
   name = "ğŸ’¸AIæ™ºèƒ½ä½“"
   weight = 3
   url = "agent/"
